<?php

use Illuminate\Database\Seeder;

class PropertyUpdatesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('property_updates')->delete();
        
        \DB::table('property_updates')->insert(array (
            0 => 
            array (
                'id' => 1,
                'property' => 2,
                'agent' => 5,
                'category' => 'Rumah',
                'isSell' => 2,
                'isRent' => NULL,
                'name' => 'Green Pramuka City',
                'bath_room' => 2,
                'bed_room' => 4,
                'stories' => 2,
                'land_area' => 100,
                'building_area' => 85,
                'location' => '11,155,1895,24904',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15973995920.webp,storage/image/property/15973995921.jpeg,storage/image/property/15973995922.jpeg,storage/image/property/15973995923.jpeg,storage/image/property/15973995924.jpeg,storage/image/property/15973995925.jpeg,storage/image/property/15973995926.jpeg',
                'main_image' => 'storage/image/property/15973995920.webp',
                'created_at' => '2020-01-17 13:19:08',
                'updated_at' => '2020-08-17 13:19:08',
            ),
            1 => 
            array (
                'id' => 2,
                'property' => 27,
                'agent' => 20,
                'category' => 'Rumah',
                'isSell' => 11,
                'isRent' => NULL,
                'name' => 'Perumahan Syariah',
                'bath_room' => 3,
                'bed_room' => 4,
                'stories' => 3,
                'land_area' => 120,
                'building_area' => 300,
                'location' => '5,92,1113,16045',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15976492790.jpeg,storage/image/property/15976492791.jpeg,storage/image/property/15976492792.jpeg,storage/image/property/15976492793.jpeg,storage/image/property/15976492794.jpeg,storage/image/property/15976492795.jpeg,storage/image/property/15976492796.jpeg',
                'main_image' => 'storage/image/property/15976492790.jpeg',
                'created_at' => '2020-02-17 13:19:13',
                'updated_at' => '2020-08-17 13:19:13',
            ),
            2 => 
            array (
                'id' => 3,
                'property' => 41,
                'agent' => 5,
                'category' => 'Rumah',
                'isSell' => 18,
                'isRent' => NULL,
                'name' => 'Green Pramuka City',
                'bath_room' => 3,
                'bed_room' => 4,
                'stories' => 3,
                'land_area' => 78,
                'building_area' => 120,
                'location' => '20,319,4614,56524',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15976521160.jpeg,storage/image/property/15976521161.png,storage/image/property/15976521162.jpeg',
                'main_image' => 'storage/image/property/15976521160.jpeg',
                'created_at' => '2020-03-17 13:19:16',
                'updated_at' => '2020-08-17 13:19:16',
            ),
            3 => 
            array (
                'id' => 4,
                'property' => 26,
                'agent' => 20,
                'category' => 'Rumah',
                'isSell' => 10,
                'isRent' => NULL,
                'name' => 'Griya Geneng',
                'bath_room' => 2,
                'bed_room' => 2,
                'stories' => 2,
                'land_area' => 60,
                'building_area' => 100,
                'location' => '9,142,1791,24255',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15976491910.jpeg,storage/image/property/15976491911.jpeg,storage/image/property/15976491912.jpeg,storage/image/property/15976491913.jpeg,storage/image/property/15976491914.jpeg,storage/image/property/15976491915.jpeg,storage/image/property/15976491916.jpeg',
                'main_image' => 'storage/image/property/15976491910.jpeg',
                'created_at' => '2020-04-17 13:19:19',
                'updated_at' => '2020-08-17 13:19:19',
            ),
            4 => 
            array (
                'id' => 5,
                'property' => 13,
                'agent' => 16,
                'category' => 'Rumah',
                'isSell' => 5,
                'isRent' => NULL,
                'name' => 'Pondok Indah',
                'bath_room' => 2,
                'bed_room' => 4,
                'stories' => 2,
                'land_area' => 100,
                'building_area' => 85,
                'location' => '11,154,1885,24839',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15974015610.jpeg,storage/image/property/15974015611.jpeg,storage/image/property/15974015612.jpeg,storage/image/property/15974015613.jpeg,storage/image/property/15974015614.jpeg,storage/image/property/15974015615.jpeg,storage/image/property/15974015616.jpeg',
                'main_image' => 'storage/image/property/15974015610.jpeg',
                'created_at' => '2020-05-17 13:19:24',
                'updated_at' => '2020-08-17 13:19:24',
            ),
            5 => 
            array (
                'id' => 6,
                'property' => 46,
                'agent' => 16,
                'category' => 'Rumah',
                'isSell' => 23,
                'isRent' => NULL,
                'name' => 'Green Pramuka City',
                'bath_room' => 1,
                'bed_room' => 2,
                'stories' => 2,
                'land_area' => 80,
                'building_area' => 75,
                'location' => '25,373,5212,63296',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15976531180.jpeg,storage/image/property/15976531181.jpeg,storage/image/property/15976531182.jpeg,storage/image/property/15976531183.webp,storage/image/property/15976531184.webp,storage/image/property/15976531185.jpeg,storage/image/property/15976531186.png',
                'main_image' => 'storage/image/property/15976531180.jpeg',
                'created_at' => '2020-06-17 13:19:28',
                'updated_at' => '2020-08-17 13:19:28',
            ),
            6 => 
            array (
                'id' => 7,
                'property' => 15,
                'agent' => 16,
                'category' => 'Rumah',
                'isSell' => 7,
                'isRent' => NULL,
                'name' => 'Perumahan Aja',
                'bath_room' => 2,
                'bed_room' => 2,
                'stories' => 2,
                'land_area' => 70,
                'building_area' => 60,
                'location' => '16,270,4010,50028',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15974017170.jpeg,storage/image/property/15974017171.jpeg,storage/image/property/15974017172.jpeg,storage/image/property/15974017173.jpeg,storage/image/property/15974017174.jpeg,storage/image/property/15974017175.jpeg,storage/image/property/15974017176.jpeg',
                'main_image' => 'storage/image/property/15974017170.jpeg',
                'created_at' => '2020-07-17 13:19:33',
                'updated_at' => '2020-08-17 13:19:33',
            ),
            7 => 
            array (
                'id' => 8,
                'property' => 28,
                'agent' => 20,
                'category' => 'Rumah',
                'isSell' => 12,
                'isRent' => NULL,
                'name' => 'Orchid Green Park , Rumah Siap Huni Tanpa DP',
                'bath_room' => 3,
                'bed_room' => 5,
                'stories' => 3,
                'land_area' => 70,
                'building_area' => 180,
                'location' => '7,119,1493,20935',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15976493720.jpeg,storage/image/property/15976493721.jpeg,storage/image/property/15976493722.jpeg,storage/image/property/15976493723.jpeg,storage/image/property/15976493724.jpeg,storage/image/property/15976493725.jpeg,storage/image/property/15976493726.jpeg',
                'main_image' => 'storage/image/property/15976493720.jpeg',
                'created_at' => '2020-08-17 13:19:39',
                'updated_at' => '2020-08-17 13:19:39',
            ),
            8 => 
            array (
                'id' => 9,
                'property' => 25,
                'agent' => 20,
                'category' => 'Rumah',
                'isSell' => 9,
                'isRent' => NULL,
                'name' => 'Green Pramuka City',
                'bath_room' => 3,
                'bed_room' => 4,
                'stories' => 2,
                'land_area' => 80,
                'building_area' => 75,
                'location' => '27,404,5590,67319',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15976490910.jpeg,storage/image/property/15976490911.jpeg,storage/image/property/15976490912.jpeg,storage/image/property/15976490913.jpeg,storage/image/property/15976490914.jpeg,storage/image/property/15976490915.jpeg,storage/image/property/15976490916.jpeg',
                'main_image' => 'storage/image/property/15976490910.jpeg',
                'created_at' => '2020-09-17 13:19:41',
                'updated_at' => '2020-08-17 13:19:41',
            ),
            9 => 
            array (
                'id' => 10,
                'property' => 40,
                'agent' => 20,
                'category' => 'Rumah',
                'isSell' => 17,
                'isRent' => NULL,
                'name' => 'Pondok Indah',
                'bath_room' => 3,
                'bed_room' => 4,
                'stories' => 2,
                'land_area' => 80,
                'building_area' => 75,
                'location' => '11,156,1903,24958',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15976518300.jpeg,storage/image/property/15976518301.png,storage/image/property/15976518302.jpeg,storage/image/property/15976518303.webp,storage/image/property/15976518304.jpeg',
                'main_image' => 'storage/image/property/15976518300.jpeg',
                'created_at' => '2020-10-17 13:19:45',
                'updated_at' => '2020-08-17 13:19:45',
            ),
            10 => 
            array (
                'id' => 11,
                'property' => 38,
                'agent' => 20,
                'category' => 'Rumah',
                'isSell' => 14,
                'isRent' => NULL,
                'name' => 'Perumahan Green',
                'bath_room' => 3,
                'bed_room' => 2,
                'stories' => 2,
                'land_area' => 80,
                'building_area' => 160,
                'location' => '22,344,4884,59611',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15976514220.jpeg,storage/image/property/15976514221.jpeg,storage/image/property/15976514222.jpeg,storage/image/property/15976514223.jpeg,storage/image/property/15976514224.webp,storage/image/property/15976514225.jpeg',
                'main_image' => 'storage/image/property/15976514220.jpeg',
                'created_at' => '2020-10-17 13:19:50',
                'updated_at' => '2020-08-17 13:19:50',
            ),
            11 => 
            array (
                'id' => 12,
                'property' => 16,
                'agent' => 16,
                'category' => 'Rumah',
                'isSell' => 8,
                'isRent' => NULL,
                'name' => 'Griya Agung Residence',
                'bath_room' => 2,
                'bed_room' => 2,
                'stories' => 2,
                'land_area' => 80,
                'building_area' => 75,
                'location' => '21,329,4717,57692',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15974018040.jpeg,storage/image/property/15974018041.jpeg,storage/image/property/15974018042.jpeg,storage/image/property/15974018043.jpeg,storage/image/property/15974018044.jpeg,storage/image/property/15974018045.jpeg,storage/image/property/15974018046.jpeg',
                'main_image' => 'storage/image/property/15974018040.jpeg',
                'created_at' => '2020-11-17 13:19:54',
                'updated_at' => '2020-08-17 13:19:54',
            ),
            12 => 
            array (
                'id' => 13,
                'property' => 43,
                'agent' => 5,
                'category' => 'Rumah',
                'isSell' => 20,
                'isRent' => NULL,
                'name' => 'GRIYA ELIVA 1',
                'bath_room' => 2,
                'bed_room' => 2,
                'stories' => 3,
                'land_area' => 100,
                'building_area' => 240,
                'location' => '19,297,4332,53080',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15976523200.jpeg,storage/image/property/15976523201.jpeg,storage/image/property/15976523202.jpeg,storage/image/property/15976523203.jpeg,storage/image/property/15976523204.webp,storage/image/property/15976523205.webp,storage/image/property/15976523206.jpeg',
                'main_image' => 'storage/image/property/15976523200.jpeg',
                'created_at' => '2020-12-17 13:20:00',
                'updated_at' => '2020-08-17 13:20:00',
            ),
            13 => 
            array (
                'id' => 14,
                'property' => 6,
                'agent' => 5,
                'category' => 'Kontrakan',
                'isSell' => NULL,
                'isRent' => 2,
                'name' => 'Green Pramuka City',
                'bath_room' => 2,
                'bed_room' => 2,
                'stories' => 2,
                'land_area' => 80,
                'building_area' => 70,
                'location' => '11,156,1904,24963',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15974004840.jpeg,storage/image/property/15974004841.jpeg,storage/image/property/15974004842.jpeg,storage/image/property/15974004843.jpeg,storage/image/property/15974004844.jpeg,storage/image/property/15974004845.webp,storage/image/property/15974004846.jpeg',
                'main_image' => 'storage/image/property/15974004840.jpeg',
                'created_at' => '2020-01-19 04:38:53',
                'updated_at' => '2020-08-19 04:38:53',
            ),
            14 => 
            array (
                'id' => 15,
                'property' => 19,
                'agent' => 16,
                'category' => 'Kontrakan',
                'isSell' => NULL,
                'isRent' => 11,
                'name' => 'Griya B',
                'bath_room' => 2,
                'bed_room' => 4,
                'stories' => 2,
                'land_area' => 120,
                'building_area' => 100,
                'location' => '14,223,3167,39906',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15974021590.jpeg,storage/image/property/15974021591.jpeg,storage/image/property/15974021592.jpeg,storage/image/property/15974021593.jpeg,storage/image/property/15974021594.jpeg,storage/image/property/15974021595.webp,storage/image/property/15974021596.jpeg',
                'main_image' => 'storage/image/property/15974021590.jpeg',
                'created_at' => '2020-02-19 04:38:57',
                'updated_at' => '2020-08-19 04:38:57',
            ),
            15 => 
            array (
                'id' => 16,
                'property' => 31,
                'agent' => 20,
                'category' => 'Kontrakan',
                'isSell' => NULL,
                'isRent' => 18,
                'name' => 'Geneng Permai',
                'bath_room' => 2,
                'bed_room' => 2,
                'stories' => 2,
                'land_area' => 80,
                'building_area' => 75,
                'location' => '17,277,4054,50509',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15976500210.jpeg,storage/image/property/15976500211.webp,storage/image/property/15976500212.jpeg,storage/image/property/15976500213.png,storage/image/property/15976500214.jpeg,storage/image/property/15976500215.webp,storage/image/property/15976500216.jpeg',
                'main_image' => 'storage/image/property/15976500210.jpeg',
                'created_at' => '2020-03-19 04:39:03',
                'updated_at' => '2020-08-19 04:39:03',
            ),
            16 => 
            array (
                'id' => 17,
                'property' => 5,
                'agent' => 5,
                'category' => 'Kontrakan',
                'isSell' => NULL,
                'isRent' => 1,
                'name' => 'Geneng Permai',
                'bath_room' => 1,
                'bed_room' => 2,
                'stories' => 1,
                'land_area' => 60,
                'building_area' => 50,
                'location' => '13,218,3105,39437',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15974000000.jpeg,storage/image/property/15974000001.jpeg,storage/image/property/15974000002.jpeg,storage/image/property/15974000003.jpeg,storage/image/property/15974000004.jpeg,storage/image/property/15974000005.jpeg,storage/image/property/15974000006.webp',
                'main_image' => 'storage/image/property/15974000000.jpeg',
                'created_at' => '2020-04-19 04:39:12',
                'updated_at' => '2020-08-19 04:39:12',
            ),
            17 => 
            array (
                'id' => 18,
                'property' => 11,
                'agent' => 5,
                'category' => 'Kos',
                'isSell' => NULL,
                'isRent' => 7,
                'name' => 'Kos  Cemara',
                'bath_room' => 3,
                'bed_room' => 1,
                'stories' => 3,
                'land_area' => 70,
                'building_area' => 180,
                'location' => '15,232,3320,41603',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15974011340.webp,storage/image/property/15974011341.jpeg,storage/image/property/15974011342.jpeg,storage/image/property/15974011343.jpeg,storage/image/property/15974011344.jpeg,storage/image/property/15974011345.jpeg,storage/image/property/15974011346.jpeg',
                'main_image' => 'storage/image/property/15974011340.webp',
                'created_at' => '2020-05-19 04:39:16',
                'updated_at' => '2020-08-19 04:39:16',
            ),
            18 => 
            array (
                'id' => 19,
                'property' => 10,
                'agent' => 5,
                'category' => 'Kos',
                'isSell' => NULL,
                'isRent' => 6,
                'name' => 'Kos Merah',
                'bath_room' => 1,
                'bed_room' => 1,
                'stories' => 1,
                'land_area' => 70,
                'building_area' => 60,
                'location' => '13,216,3093,39325',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15974010120.jpeg,storage/image/property/15974010121.webp,storage/image/property/15974010122.jpeg,storage/image/property/15974010123.jpeg,storage/image/property/15974010124.jpeg,storage/image/property/15974010125.jpeg,storage/image/property/15974010126.jpeg',
                'main_image' => 'storage/image/property/15974010120.jpeg',
                'created_at' => '2020-06-19 04:39:18',
                'updated_at' => '2020-08-19 04:39:18',
            ),
            19 => 
            array (
                'id' => 20,
                'property' => 22,
                'agent' => 16,
                'category' => 'Kos',
                'isSell' => NULL,
                'isRent' => 14,
                'name' => 'Kos ABC',
                'bath_room' => 2,
                'bed_room' => 1,
                'stories' => 2,
                'land_area' => 60,
                'building_area' => 80,
                'location' => '11,154,1884,24834',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15974036120.jpeg,storage/image/property/15974036121.jpeg,storage/image/property/15974036122.webp,storage/image/property/15974036123.jpeg,storage/image/property/15974036124.png,storage/image/property/15974036125.jpeg,storage/image/property/15974036126.webp',
                'main_image' => 'storage/image/property/15974036120.jpeg',
                'created_at' => '2020-07-19 04:39:24',
                'updated_at' => '2020-08-19 04:39:24',
            ),
            20 => 
            array (
                'id' => 21,
                'property' => 20,
                'agent' => 16,
                'category' => 'Kontrakan',
                'isSell' => NULL,
                'isRent' => 12,
                'name' => 'Griya C',
                'bath_room' => 1,
                'bed_room' => 2,
                'stories' => 2,
                'land_area' => 150,
                'building_area' => 120,
                'location' => '1,14,219,5153',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15974022990.jpeg,storage/image/property/15974022991.jpeg,storage/image/property/15974022992.jpeg,storage/image/property/15974022993.jpeg,storage/image/property/15974022994.webp,storage/image/property/15974022995.jpeg,storage/image/property/15974022996.jpeg',
                'main_image' => 'storage/image/property/15974022990.jpeg',
                'created_at' => '2020-08-19 04:39:27',
                'updated_at' => '2020-08-19 04:39:27',
            ),
            21 => 
            array (
                'id' => 22,
                'property' => 23,
                'agent' => 16,
                'category' => 'Kos',
                'isSell' => NULL,
                'isRent' => 15,
                'name' => 'Kos FGH',
                'bath_room' => 6,
                'bed_room' => 1,
                'stories' => 3,
                'land_area' => 100,
                'building_area' => 240,
                'location' => '22,348,4925,60251',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15974037390.jpeg,storage/image/property/15974037391.webp,storage/image/property/15974037392.jpeg,storage/image/property/15974037393.png,storage/image/property/15974037394.jpeg,storage/image/property/15974037395.webp,storage/image/property/15974037396.jpeg',
                'main_image' => 'storage/image/property/15974037390.jpeg',
                'created_at' => '2020-09-19 04:39:31',
                'updated_at' => '2020-08-19 04:39:31',
            ),
            22 => 
            array (
                'id' => 23,
                'property' => 34,
                'agent' => 20,
                'category' => 'Kos',
                'isSell' => NULL,
                'isRent' => 21,
                'name' => 'Kos Zahira',
                'bath_room' => 2,
                'bed_room' => 1,
                'stories' => 1,
                'land_area' => 70,
                'building_area' => 60,
                'location' => '13,199,2830,35231',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15976505610.jpeg,storage/image/property/15976505611.jpeg,storage/image/property/15976505612.jpeg,storage/image/property/15976505613.jpeg,storage/image/property/15976505614.jpeg,storage/image/property/15976505615.jpeg',
                'main_image' => 'storage/image/property/15976505610.jpeg',
                'created_at' => '2020-10-19 04:39:40',
                'updated_at' => '2020-08-19 04:39:40',
            ),
            23 => 
            array (
                'id' => 24,
                'property' => 37,
                'agent' => 20,
                'category' => 'Kos',
                'isSell' => NULL,
                'isRent' => 26,
                'name' => 'Kos Kuning',
                'bath_room' => 1,
                'bed_room' => 1,
                'stories' => 1,
                'land_area' => 80,
                'building_area' => 75,
                'location' => '15,241,3541,44210',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15976510750.jpeg,storage/image/property/15976510751.jpeg,storage/image/property/15976510752.jpeg,storage/image/property/15976510753.jpeg,storage/image/property/15976510764.jpeg,storage/image/property/15976510765.jpeg,storage/image/property/15976510766.jpeg',
                'main_image' => 'storage/image/property/15976510750.jpeg',
                'created_at' => '2020-11-19 04:39:44',
                'updated_at' => '2020-08-19 04:39:44',
            ),
            24 => 
            array (
                'id' => 25,
                'property' => 24,
                'agent' => 16,
                'category' => 'Kos',
                'isSell' => NULL,
                'isRent' => 16,
                'name' => 'Kos IJK',
                'bath_room' => 2,
                'bed_room' => 1,
                'stories' => 1,
                'land_area' => 80,
                'building_area' => 60,
                'location' => '12,163,2077,26564',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15974038170.webp,storage/image/property/15974038171.jpeg,storage/image/property/15974038172.png,storage/image/property/15974038173.jpeg,storage/image/property/15974038174.webp,storage/image/property/15974038175.jpeg,storage/image/property/15974038176.jpeg',
                'main_image' => 'storage/image/property/15974038170.webp',
                'created_at' => '2020-12-19 04:39:51',
                'updated_at' => '2020-08-19 04:39:51',
            ),
        ));
        
        
    }
}