<?php

use Illuminate\Database\Seeder;

class PropertiesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('properties')->delete();
        
        \DB::table('properties')->insert(array (
            0 => 
            array (
                'id' => 1,
                'agent' => 5,
                'category' => 'Rumah',
                'isSell' => 1,
                'isRent' => NULL,
                'name' => 'Rumah HIJAU LUAS',
                'bath_room' => 2,
                'bed_room' => 2,
                'stories' => 1,
                'land_area' => 80,
                'building_area' => 60,
                'location' => '14,223,3164,39875',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15973994020.jpeg,storage/image/property/15973994031.webp,storage/image/property/15973994032.jpeg,storage/image/property/15973994033.jpeg,storage/image/property/15973994034.jpeg,storage/image/property/15973994035.jpeg,storage/image/property/15973994036.jpeg',
                'main_image' => 'storage/image/property/15973994020.jpeg',
                'created_at' => '2020-08-14 10:03:23',
                'updated_at' => '2020-08-14 10:03:23',
            ),
            1 => 
            array (
                'id' => 3,
                'agent' => 5,
                'category' => 'Rumah',
                'isSell' => 3,
                'isRent' => NULL,
                'name' => 'Perumahan Syariah',
                'bath_room' => 3,
                'bed_room' => 3,
                'stories' => 3,
                'land_area' => 95,
                'building_area' => 120,
                'location' => '11,156,1907,24976',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15973997750.jpeg,storage/image/property/15973997751.jpeg,storage/image/property/15973997752.jpeg,storage/image/property/15973997753.jpeg,storage/image/property/15973997754.jpeg,storage/image/property/15973997755.jpeg,storage/image/property/15973997756.jpeg',
                'main_image' => 'storage/image/property/15973997750.jpeg',
                'created_at' => '2020-08-14 10:09:35',
                'updated_at' => '2020-08-14 10:09:35',
            ),
            2 => 
            array (
                'id' => 4,
                'agent' => 5,
                'category' => 'Rumah',
                'isSell' => 4,
                'isRent' => NULL,
                'name' => 'Griya Geneng',
                'bath_room' => 2,
                'bed_room' => 4,
                'stories' => 1,
                'land_area' => 150,
                'building_area' => 100,
                'location' => '15,262,3833,48389',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15973999140.jpeg,storage/image/property/15973999141.jpeg,storage/image/property/15973999142.jpeg,storage/image/property/15973999143.jpeg,storage/image/property/15973999144.jpeg,storage/image/property/15973999145.jpeg,storage/image/property/15973999146.jpeg',
                'main_image' => 'storage/image/property/15973999140.jpeg',
                'created_at' => '2020-08-14 10:11:54',
                'updated_at' => '2020-08-14 10:11:54',
            ),
            3 => 
            array (
                'id' => 5,
                'agent' => 5,
                'category' => 'Kontrakan',
                'isSell' => NULL,
                'isRent' => 1,
                'name' => 'Geneng Permai',
                'bath_room' => 1,
                'bed_room' => 2,
                'stories' => 1,
                'land_area' => 60,
                'building_area' => 50,
                'location' => '13,218,3105,39437',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15974000000.jpeg,storage/image/property/15974000001.jpeg,storage/image/property/15974000002.jpeg,storage/image/property/15974000003.jpeg,storage/image/property/15974000004.jpeg,storage/image/property/15974000005.jpeg,storage/image/property/15974000006.webp',
                'main_image' => 'storage/image/property/15974000000.jpeg',
                'created_at' => '2020-08-14 10:13:20',
                'updated_at' => '2020-08-14 10:13:20',
            ),
            4 => 
            array (
                'id' => 6,
                'agent' => 5,
                'category' => 'Kontrakan',
                'isSell' => NULL,
                'isRent' => 2,
                'name' => 'Green Pramuka City',
                'bath_room' => 2,
                'bed_room' => 2,
                'stories' => 2,
                'land_area' => 80,
                'building_area' => 70,
                'location' => '11,156,1904,24963',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15974004840.jpeg,storage/image/property/15974004841.jpeg,storage/image/property/15974004842.jpeg,storage/image/property/15974004843.jpeg,storage/image/property/15974004844.jpeg,storage/image/property/15974004845.webp,storage/image/property/15974004846.jpeg',
                'main_image' => 'storage/image/property/15974004840.jpeg',
                'created_at' => '2020-08-14 10:21:24',
                'updated_at' => '2020-08-14 10:21:24',
            ),
            5 => 
            array (
                'id' => 7,
                'agent' => 5,
                'category' => 'Rumah',
                'isSell' => NULL,
                'isRent' => 3,
                'name' => 'Perumahan Indah',
                'bath_room' => 1,
                'bed_room' => 2,
                'stories' => 2,
                'land_area' => 60,
                'building_area' => 80,
                'location' => '13,198,2805,34957',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15974005810.jpeg,storage/image/property/15974005811.jpeg,storage/image/property/15974005812.jpeg,storage/image/property/15974005813.jpeg,storage/image/property/15974005814.webp,storage/image/property/15974005815.jpeg,storage/image/property/15974005816.jpeg',
                'main_image' => 'storage/image/property/15974005810.jpeg',
                'created_at' => '2020-08-14 10:23:01',
                'updated_at' => '2020-08-14 10:23:01',
            ),
            6 => 
            array (
                'id' => 8,
                'agent' => 5,
                'category' => 'Kontrakan',
                'isSell' => NULL,
                'isRent' => 4,
                'name' => 'Perumahan Green',
                'bath_room' => 2,
                'bed_room' => 4,
                'stories' => 1,
                'land_area' => 100,
                'building_area' => 80,
                'location' => '15,262,3837,48407',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15974007600.jpeg,storage/image/property/15974007601.jpeg,storage/image/property/15974007602.jpeg,storage/image/property/15974007603.webp,storage/image/property/15974007604.jpeg,storage/image/property/15974007605.jpeg,storage/image/property/15974007606.jpeg',
                'main_image' => 'storage/image/property/15974007600.jpeg',
                'created_at' => '2020-08-14 10:26:00',
                'updated_at' => '2020-08-14 10:26:00',
            ),
            7 => 
            array (
                'id' => 9,
                'agent' => 5,
                'category' => 'Kos',
                'isSell' => NULL,
                'isRent' => 5,
                'name' => 'Kos Kuning',
                'bath_room' => 1,
                'bed_room' => 1,
                'stories' => 1,
                'land_area' => 80,
                'building_area' => 70,
                'location' => '12,174,2426,30204',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15974008790.jpeg,storage/image/property/15974008791.jpeg,storage/image/property/15974008792.webp,storage/image/property/15974008793.jpeg,storage/image/property/15974008794.jpeg,storage/image/property/15974008795.jpeg,storage/image/property/15974008796.jpeg',
                'main_image' => 'storage/image/property/15974008790.jpeg',
                'created_at' => '2020-08-14 10:27:59',
                'updated_at' => '2020-08-14 10:27:59',
            ),
            8 => 
            array (
                'id' => 10,
                'agent' => 5,
                'category' => 'Kos',
                'isSell' => NULL,
                'isRent' => 6,
                'name' => 'Kos Merah',
                'bath_room' => 1,
                'bed_room' => 1,
                'stories' => 1,
                'land_area' => 70,
                'building_area' => 60,
                'location' => '13,216,3093,39325',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15974010120.jpeg,storage/image/property/15974010121.webp,storage/image/property/15974010122.jpeg,storage/image/property/15974010123.jpeg,storage/image/property/15974010124.jpeg,storage/image/property/15974010125.jpeg,storage/image/property/15974010126.jpeg',
                'main_image' => 'storage/image/property/15974010120.jpeg',
                'created_at' => '2020-08-14 10:30:12',
                'updated_at' => '2020-08-14 10:30:12',
            ),
            9 => 
            array (
                'id' => 11,
                'agent' => 5,
                'category' => 'Kos',
                'isSell' => NULL,
                'isRent' => 7,
                'name' => 'Kos  Cemara',
                'bath_room' => 3,
                'bed_room' => 1,
                'stories' => 3,
                'land_area' => 70,
                'building_area' => 180,
                'location' => '15,232,3320,41603',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15974011340.webp,storage/image/property/15974011341.jpeg,storage/image/property/15974011342.jpeg,storage/image/property/15974011343.jpeg,storage/image/property/15974011344.jpeg,storage/image/property/15974011345.jpeg,storage/image/property/15974011346.jpeg',
                'main_image' => 'storage/image/property/15974011340.webp',
                'created_at' => '2020-08-14 10:32:14',
                'updated_at' => '2020-08-14 10:32:14',
            ),
            10 => 
            array (
                'id' => 12,
                'agent' => 5,
                'category' => 'Kos',
                'isSell' => NULL,
                'isRent' => 8,
                'name' => 'Kos Zahira',
                'bath_room' => 2,
                'bed_room' => 1,
                'stories' => 1,
                'land_area' => 60,
                'building_area' => 60,
                'location' => '15,257,3816,48262',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15974012270.jpeg,storage/image/property/15974012271.jpeg,storage/image/property/15974012272.jpeg,storage/image/property/15974012273.jpeg,storage/image/property/15974012274.jpeg,storage/image/property/15974012275.jpeg,storage/image/property/15974012276.jpeg',
                'main_image' => 'storage/image/property/15974012270.jpeg',
                'created_at' => '2020-08-14 10:33:47',
                'updated_at' => '2020-08-14 10:33:47',
            ),
            11 => 
            array (
                'id' => 14,
                'agent' => 16,
                'category' => 'Rumah',
                'isSell' => 6,
                'isRent' => NULL,
                'name' => 'Perumahan Elit',
                'bath_room' => 3,
                'bed_room' => 3,
                'stories' => 2,
                'land_area' => 80,
                'building_area' => 70,
                'location' => '16,268,3990,49882',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15974016450.jpeg,storage/image/property/15974016451.jpeg,storage/image/property/15974016452.jpeg,storage/image/property/15974016453.jpeg,storage/image/property/15974016454.jpeg,storage/image/property/15974016455.jpeg,storage/image/property/15974016456.jpeg',
                'main_image' => 'storage/image/property/15974016450.jpeg',
                'created_at' => '2020-08-14 10:40:45',
                'updated_at' => '2020-08-14 10:40:45',
            ),
            12 => 
            array (
                'id' => 17,
                'agent' => 16,
                'category' => 'Kontrakan',
                'isSell' => NULL,
                'isRent' => 9,
                'name' => 'GRIYA ELIVA',
                'bath_room' => 1,
                'bed_room' => 2,
                'stories' => 1,
                'land_area' => 60,
                'building_area' => 60,
                'location' => '15,241,3541,44210',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15974019880.jpeg,storage/image/property/15974019881.jpeg,storage/image/property/15974019882.jpeg,storage/image/property/15974019883.jpeg,storage/image/property/15974019884.jpeg,storage/image/property/15974019885.jpeg,storage/image/property/15974019886.jpeg',
                'main_image' => 'storage/image/property/15974019880.jpeg',
                'created_at' => '2020-08-14 10:46:29',
                'updated_at' => '2020-08-14 10:46:29',
            ),
            13 => 
            array (
                'id' => 18,
                'agent' => 16,
                'category' => 'Kontrakan',
                'isSell' => NULL,
                'isRent' => 10,
                'name' => 'Griya A',
                'bath_room' => 1,
                'bed_room' => 1,
                'stories' => 1,
                'land_area' => 50,
                'building_area' => 50,
                'location' => '8,134,1722,23659',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15974020840.jpeg,storage/image/property/15974020841.jpeg,storage/image/property/15974020842.jpeg,storage/image/property/15974020843.jpeg,storage/image/property/15974020844.jpeg,storage/image/property/15974020845.jpeg,storage/image/property/15974020846.webp',
                'main_image' => 'storage/image/property/15974020840.jpeg',
                'created_at' => '2020-08-14 10:48:04',
                'updated_at' => '2020-08-14 10:48:04',
            ),
            14 => 
            array (
                'id' => 19,
                'agent' => 16,
                'category' => 'Kontrakan',
                'isSell' => NULL,
                'isRent' => 11,
                'name' => 'Griya B',
                'bath_room' => 2,
                'bed_room' => 4,
                'stories' => 2,
                'land_area' => 120,
                'building_area' => 100,
                'location' => '14,223,3167,39906',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15974021590.jpeg,storage/image/property/15974021591.jpeg,storage/image/property/15974021592.jpeg,storage/image/property/15974021593.jpeg,storage/image/property/15974021594.jpeg,storage/image/property/15974021595.webp,storage/image/property/15974021596.jpeg',
                'main_image' => 'storage/image/property/15974021590.jpeg',
                'created_at' => '2020-08-14 10:49:19',
                'updated_at' => '2020-08-14 10:49:19',
            ),
            15 => 
            array (
                'id' => 20,
                'agent' => 16,
                'category' => 'Kontrakan',
                'isSell' => NULL,
                'isRent' => 12,
                'name' => 'Griya C',
                'bath_room' => 1,
                'bed_room' => 2,
                'stories' => 2,
                'land_area' => 150,
                'building_area' => 120,
                'location' => '1,14,219,5153',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15974022990.jpeg,storage/image/property/15974022991.jpeg,storage/image/property/15974022992.jpeg,storage/image/property/15974022993.jpeg,storage/image/property/15974022994.webp,storage/image/property/15974022995.jpeg,storage/image/property/15974022996.jpeg',
                'main_image' => 'storage/image/property/15974022990.jpeg',
                'created_at' => '2020-08-14 10:51:39',
                'updated_at' => '2020-08-14 10:51:39',
            ),
            16 => 
            array (
                'id' => 21,
                'agent' => 16,
                'category' => 'Kos',
                'isSell' => NULL,
                'isRent' => 13,
                'name' => 'Kos Zahira Adel',
                'bath_room' => 2,
                'bed_room' => 1,
                'stories' => 2,
                'land_area' => 70,
                'building_area' => 60,
                'location' => '25,369,5153,62705',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15974024460.jpeg,storage/image/property/15974024461.jpeg,storage/image/property/15974024462.jpeg,storage/image/property/15974024463.webp,storage/image/property/15974024464.jpeg,storage/image/property/15974024465.jpeg,storage/image/property/15974024466.webp',
                'main_image' => 'storage/image/property/15974024460.jpeg',
                'created_at' => '2020-08-14 10:54:06',
                'updated_at' => '2020-08-14 10:54:06',
            ),
            17 => 
            array (
                'id' => 22,
                'agent' => 16,
                'category' => 'Kos',
                'isSell' => NULL,
                'isRent' => 14,
                'name' => 'Kos ABC',
                'bath_room' => 2,
                'bed_room' => 1,
                'stories' => 2,
                'land_area' => 60,
                'building_area' => 80,
                'location' => '11,154,1884,24834',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15974036120.jpeg,storage/image/property/15974036121.jpeg,storage/image/property/15974036122.webp,storage/image/property/15974036123.jpeg,storage/image/property/15974036124.png,storage/image/property/15974036125.jpeg,storage/image/property/15974036126.webp',
                'main_image' => 'storage/image/property/15974036120.jpeg',
                'created_at' => '2020-08-14 11:13:32',
                'updated_at' => '2020-08-14 11:13:32',
            ),
            18 => 
            array (
                'id' => 23,
                'agent' => 16,
                'category' => 'Kos',
                'isSell' => NULL,
                'isRent' => 15,
                'name' => 'Kos FGH',
                'bath_room' => 6,
                'bed_room' => 1,
                'stories' => 3,
                'land_area' => 100,
                'building_area' => 240,
                'location' => '22,348,4925,60251',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15974037390.jpeg,storage/image/property/15974037391.webp,storage/image/property/15974037392.jpeg,storage/image/property/15974037393.png,storage/image/property/15974037394.jpeg,storage/image/property/15974037395.webp,storage/image/property/15974037396.jpeg',
                'main_image' => 'storage/image/property/15974037390.jpeg',
                'created_at' => '2020-08-14 11:15:39',
                'updated_at' => '2020-08-14 11:15:39',
            ),
            19 => 
            array (
                'id' => 24,
                'agent' => 16,
                'category' => 'Kos',
                'isSell' => NULL,
                'isRent' => 16,
                'name' => 'Kos IJK',
                'bath_room' => 2,
                'bed_room' => 1,
                'stories' => 1,
                'land_area' => 80,
                'building_area' => 60,
                'location' => '12,163,2077,26564',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15974038170.webp,storage/image/property/15974038171.jpeg,storage/image/property/15974038172.png,storage/image/property/15974038173.jpeg,storage/image/property/15974038174.webp,storage/image/property/15974038175.jpeg,storage/image/property/15974038176.jpeg',
                'main_image' => 'storage/image/property/15974038170.webp',
                'created_at' => '2020-08-14 11:16:57',
                'updated_at' => '2020-08-14 11:16:57',
            ),
            20 => 
            array (
                'id' => 29,
                'agent' => 20,
                'category' => 'Rumah',
                'isSell' => 13,
                'isRent' => NULL,
                'name' => 'Griya Agung Residence',
                'bath_room' => 1,
                'bed_room' => 1,
                'stories' => 2,
                'land_area' => 60,
                'building_area' => 100,
                'location' => '22,347,4915,60049',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15976494680.jpeg,storage/image/property/15976494681.jpeg,storage/image/property/15976494682.jpeg,storage/image/property/15976494683.jpeg,storage/image/property/15976494684.jpeg,storage/image/property/15976494685.jpeg,storage/image/property/15976494686.jpeg',
                'main_image' => 'storage/image/property/15976494680.jpeg',
                'created_at' => '2020-08-17 07:31:08',
                'updated_at' => '2020-08-17 07:31:08',
            ),
            21 => 
            array (
                'id' => 30,
                'agent' => 20,
                'category' => 'Kontrakan',
                'isSell' => NULL,
                'isRent' => 17,
                'name' => 'GRIYA ELIVA',
                'bath_room' => 1,
                'bed_room' => 2,
                'stories' => 1,
                'land_area' => 70,
                'building_area' => 55,
                'location' => '6,101,1233,17446',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15976499150.webp,storage/image/property/15976499151.jpeg,storage/image/property/15976499162.png,storage/image/property/15976499163.jpeg,storage/image/property/15976499164.webp,storage/image/property/15976499165.jpeg',
                'main_image' => 'storage/image/property/15976499150.webp',
                'created_at' => '2020-08-17 07:38:36',
                'updated_at' => '2020-08-17 07:38:36',
            ),
            22 => 
            array (
                'id' => 31,
                'agent' => 20,
                'category' => 'Kontrakan',
                'isSell' => NULL,
                'isRent' => 18,
                'name' => 'Geneng Permai',
                'bath_room' => 2,
                'bed_room' => 2,
                'stories' => 2,
                'land_area' => 80,
                'building_area' => 75,
                'location' => '17,277,4054,50509',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15976500210.jpeg,storage/image/property/15976500211.webp,storage/image/property/15976500212.jpeg,storage/image/property/15976500213.png,storage/image/property/15976500214.jpeg,storage/image/property/15976500215.webp,storage/image/property/15976500216.jpeg',
                'main_image' => 'storage/image/property/15976500210.jpeg',
                'created_at' => '2020-08-17 07:40:21',
                'updated_at' => '2020-08-17 07:40:21',
            ),
            23 => 
            array (
                'id' => 32,
                'agent' => 20,
                'category' => 'Kontrakan',
                'isSell' => NULL,
                'isRent' => 19,
                'name' => 'Griya abc',
                'bath_room' => 1,
                'bed_room' => 2,
                'stories' => 1,
                'land_area' => 60,
                'building_area' => 50,
                'location' => '15,242,3564,44567',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15976502140.webp,storage/image/property/15976502141.webp,storage/image/property/15976502142.jpeg,storage/image/property/15976502143.png,storage/image/property/15976502144.jpeg,storage/image/property/15976502145.webp,storage/image/property/15976502146.jpeg',
                'main_image' => 'storage/image/property/15976502140.webp',
                'created_at' => '2020-08-17 07:43:34',
                'updated_at' => '2020-08-17 07:43:34',
            ),
            24 => 
            array (
                'id' => 33,
                'agent' => 20,
                'category' => 'Kontrakan',
                'isSell' => NULL,
                'isRent' => 20,
                'name' => 'Griya efg',
                'bath_room' => 2,
                'bed_room' => 4,
                'stories' => 2,
                'land_area' => 120,
                'building_area' => 200,
                'location' => '17,277,4054,50509',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15976503050.jpeg,storage/image/property/15976503051.jpeg,storage/image/property/15976503052.jpeg,storage/image/property/15976503053.jpeg,storage/image/property/15976503054.jpeg,storage/image/property/15976503055.webp,storage/image/property/15976503056.webp',
                'main_image' => 'storage/image/property/15976503050.jpeg',
                'created_at' => '2020-08-17 07:45:05',
                'updated_at' => '2020-08-17 07:45:05',
            ),
            25 => 
            array (
                'id' => 34,
                'agent' => 20,
                'category' => 'Kos',
                'isSell' => NULL,
                'isRent' => 21,
                'name' => 'Kos Zahira',
                'bath_room' => 2,
                'bed_room' => 1,
                'stories' => 1,
                'land_area' => 70,
                'building_area' => 60,
                'location' => '13,199,2830,35231',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15976505610.jpeg,storage/image/property/15976505611.jpeg,storage/image/property/15976505612.jpeg,storage/image/property/15976505613.jpeg,storage/image/property/15976505614.jpeg,storage/image/property/15976505615.jpeg',
                'main_image' => 'storage/image/property/15976505610.jpeg',
                'created_at' => '2020-08-17 07:49:21',
                'updated_at' => '2020-08-17 07:49:21',
            ),
            26 => 
            array (
                'id' => 35,
                'agent' => 20,
                'category' => 'Kos',
                'isSell' => NULL,
                'isRent' => 22,
                'name' => 'Kos Merah',
                'bath_room' => 4,
                'bed_room' => 1,
                'stories' => 2,
                'land_area' => 80,
                'building_area' => 140,
                'location' => '29,431,5993,71453',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15976506950.jpeg,storage/image/property/15976506951.jpeg,storage/image/property/15976506952.jpeg,storage/image/property/15976506953.jpeg,storage/image/property/15976506954.jpeg,storage/image/property/15976506955.jpeg,storage/image/property/15976506956.webp',
                'main_image' => 'storage/image/property/15976506950.jpeg',
                'created_at' => '2020-08-17 07:51:35',
                'updated_at' => '2020-08-17 07:51:35',
            ),
            27 => 
            array (
                'id' => 36,
                'agent' => 20,
                'category' => 'Kos',
                'isSell' => NULL,
                'isRent' => 25,
                'name' => 'Kos Merah',
                'bath_room' => 1,
                'bed_room' => 1,
                'stories' => 2,
                'land_area' => 60,
                'building_area' => 100,
                'location' => '32,453,6221,73756',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15976509200.webp,storage/image/property/15976509201.jpeg,storage/image/property/15976509202.jpeg,storage/image/property/15976509203.jpeg,storage/image/property/15976509204.jpeg,storage/image/property/15976509205.jpeg,storage/image/property/15976509206.jpeg',
                'main_image' => 'storage/image/property/15976509200.webp',
                'created_at' => '2020-08-17 07:55:20',
                'updated_at' => '2020-08-17 07:55:20',
            ),
            28 => 
            array (
                'id' => 37,
                'agent' => 20,
                'category' => 'Kos',
                'isSell' => NULL,
                'isRent' => 26,
                'name' => 'Kos Kuning',
                'bath_room' => 1,
                'bed_room' => 1,
                'stories' => 1,
                'land_area' => 80,
                'building_area' => 75,
                'location' => '15,241,3541,44210',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15976510750.jpeg,storage/image/property/15976510751.jpeg,storage/image/property/15976510752.jpeg,storage/image/property/15976510753.jpeg,storage/image/property/15976510764.jpeg,storage/image/property/15976510765.jpeg,storage/image/property/15976510766.jpeg',
                'main_image' => 'storage/image/property/15976510750.jpeg',
                'created_at' => '2020-08-17 07:57:56',
                'updated_at' => '2020-08-17 07:57:56',
            ),
            29 => 
            array (
                'id' => 39,
                'agent' => 20,
                'category' => 'Rumah',
                'isSell' => 15,
                'isRent' => NULL,
                'name' => 'Perumahan Permai',
                'bath_room' => 1,
                'bed_room' => 1,
                'stories' => 2,
                'land_area' => 100,
                'building_area' => 80,
                'location' => '14,222,3147,39762',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15976516750.webp,storage/image/property/15976516751.jpeg,storage/image/property/15976516752.png,storage/image/property/15976516753.jpeg,storage/image/property/15976516754.webp,storage/image/property/15976516755.jpeg',
                'main_image' => 'storage/image/property/15976516750.webp',
                'created_at' => '2020-08-17 08:07:55',
                'updated_at' => '2020-08-17 08:07:55',
            ),
            30 => 
            array (
                'id' => 42,
                'agent' => 5,
                'category' => 'Rumah',
                'isSell' => 19,
                'isRent' => NULL,
                'name' => 'RUMAH MINIMALIS, SIAP HUNI',
                'bath_room' => 1,
                'bed_room' => 2,
                'stories' => 1,
                'land_area' => 65,
                'building_area' => 50,
                'location' => '8,129,1656,22811',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15976521910.webp,storage/image/property/15976521911.jpeg',
                'main_image' => 'storage/image/property/15976521910.webp',
                'created_at' => '2020-08-17 08:16:31',
                'updated_at' => '2020-08-17 08:16:31',
            ),
            31 => 
            array (
                'id' => 44,
                'agent' => 5,
                'category' => 'Rumah',
                'isSell' => 21,
                'isRent' => NULL,
                'name' => 'Perumahan Indah',
                'bath_room' => 1,
                'bed_room' => 3,
                'stories' => 1,
                'land_area' => 100,
                'building_area' => 85,
                'location' => '20,316,4562,55794',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15976524120.jpeg,storage/image/property/15976524121.webp,storage/image/property/15976524122.jpeg',
                'main_image' => 'storage/image/property/15976524120.jpeg',
                'created_at' => '2020-08-17 08:20:12',
                'updated_at' => '2020-08-17 08:20:12',
            ),
            32 => 
            array (
                'id' => 45,
                'agent' => 16,
                'category' => 'Rumah',
                'isSell' => 22,
                'isRent' => NULL,
                'name' => 'Perumahan Green',
                'bath_room' => 1,
                'bed_room' => 2,
                'stories' => 1,
                'land_area' => 70,
                'building_area' => 60,
                'location' => '15,238,3478,43163',
                'address' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
                'image' => 'storage/image/property/15976530180.jpeg',
                'main_image' => 'storage/image/property/15976530180.jpeg',
                'created_at' => '2020-08-17 08:30:18',
                'updated_at' => '2020-08-17 08:30:18',
            ),
        ));
        
        
    }
}